# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64\x62.proto\"\x1f\n\x0e\x65xecute_db_msg\x12\r\n\x05query\x18\x01 \x01(\t\" \n\x0cresponse_msg\x12\x10\n\x08response\x18\x01 \x01(\t2<\n\nexecute_db\x12.\n\nexecute_db\x12\x0f.execute_db_msg\x1a\r.response_msg\"\x00\x62\x06proto3')



_EXECUTE_DB_MSG = DESCRIPTOR.message_types_by_name['execute_db_msg']
_RESPONSE_MSG = DESCRIPTOR.message_types_by_name['response_msg']
execute_db_msg = _reflection.GeneratedProtocolMessageType('execute_db_msg', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTE_DB_MSG,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:execute_db_msg)
  })
_sym_db.RegisterMessage(execute_db_msg)

response_msg = _reflection.GeneratedProtocolMessageType('response_msg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_MSG,
  '__module__' : 'db_pb2'
  # @@protoc_insertion_point(class_scope:response_msg)
  })
_sym_db.RegisterMessage(response_msg)

_EXECUTE_DB = DESCRIPTOR.services_by_name['execute_db']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXECUTE_DB_MSG._serialized_start=12
  _EXECUTE_DB_MSG._serialized_end=43
  _RESPONSE_MSG._serialized_start=45
  _RESPONSE_MSG._serialized_end=77
  _EXECUTE_DB._serialized_start=79
  _EXECUTE_DB._serialized_end=139
# @@protoc_insertion_point(module_scope)
