# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_guide.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='route_guide.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11route_guide.proto\"\x1e\n\x0bread_db_msg\x12\x0f\n\x07\x64\x62_name\x18\x01 \x01(\t\"0\n\x0cwrite_db_msg\x12\x0f\n\x07\x64\x62_name\x18\x01 \x01(\t\x12\x0f\n\x07\x65ntries\x18\x02 \x01(\t\" \n\x0cresponse_msg\x12\x10\n\x08response\x18\x01 \x01(\t23\n\x07read_db\x12(\n\x07read_db\x12\x0c.read_db_msg\x1a\r.response_msg\"\x00\x32\x36\n\x08write_db\x12*\n\x08write_db\x12\r.write_db_msg\x1a\r.response_msg\"\x00\x62\x06proto3'
)




_READ_DB_MSG = _descriptor.Descriptor(
  name='read_db_msg',
  full_name='read_db_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_name', full_name='read_db_msg.db_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=51,
)


_WRITE_DB_MSG = _descriptor.Descriptor(
  name='write_db_msg',
  full_name='write_db_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_name', full_name='write_db_msg.db_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entries', full_name='write_db_msg.entries', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=101,
)


_RESPONSE_MSG = _descriptor.Descriptor(
  name='response_msg',
  full_name='response_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='response_msg.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['read_db_msg'] = _READ_DB_MSG
DESCRIPTOR.message_types_by_name['write_db_msg'] = _WRITE_DB_MSG
DESCRIPTOR.message_types_by_name['response_msg'] = _RESPONSE_MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

read_db_msg = _reflection.GeneratedProtocolMessageType('read_db_msg', (_message.Message,), {
  'DESCRIPTOR' : _READ_DB_MSG,
  '__module__' : 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:read_db_msg)
  })
_sym_db.RegisterMessage(read_db_msg)

write_db_msg = _reflection.GeneratedProtocolMessageType('write_db_msg', (_message.Message,), {
  'DESCRIPTOR' : _WRITE_DB_MSG,
  '__module__' : 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:write_db_msg)
  })
_sym_db.RegisterMessage(write_db_msg)

response_msg = _reflection.GeneratedProtocolMessageType('response_msg', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_MSG,
  '__module__' : 'route_guide_pb2'
  # @@protoc_insertion_point(class_scope:response_msg)
  })
_sym_db.RegisterMessage(response_msg)



_READ_DB = _descriptor.ServiceDescriptor(
  name='read_db',
  full_name='read_db',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=137,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='read_db',
    full_name='read_db.read_db',
    index=0,
    containing_service=None,
    input_type=_READ_DB_MSG,
    output_type=_RESPONSE_MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_READ_DB)

DESCRIPTOR.services_by_name['read_db'] = _READ_DB


_WRITE_DB = _descriptor.ServiceDescriptor(
  name='write_db',
  full_name='write_db',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=190,
  serialized_end=244,
  methods=[
  _descriptor.MethodDescriptor(
    name='write_db',
    full_name='write_db.write_db',
    index=0,
    containing_service=None,
    input_type=_WRITE_DB_MSG,
    output_type=_RESPONSE_MSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WRITE_DB)

DESCRIPTOR.services_by_name['write_db'] = _WRITE_DB

# @@protoc_insertion_point(module_scope)
