apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientside-buyer
  labels:
    app: buyer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyer
  template:
    metadata:
      labels:
        app: buyer
    spec:
      containers:
      - name: buyer
        image: arpitaambavane89/clientside-buyer:v1
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq