apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientside-seller
  labels:
    app: seller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller
  template:
    metadata:
      labels:
        app: seller
    spec:
      containers:
      - name: seller
        image: arpitaambavane89/clientside-seller:v1
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq